pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: VSBuild@1
  displayName: Build
  inputs:
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/restore /bl:"$(Build.ArtifactStagingDirectory)/Logs/build.binlog"'

- task: VSBuild@1
  displayName: Publish
  inputs:
    solution: Sideways
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:Publish /p:PublishDir="$(Build.ArtifactStagingDirectory)/Bin" /bl:"$(Build.ArtifactStagingDirectory)/Logs/publish.binlog"'

- task: PublishBuildArtifacts@1
  displayName: Publish bin artifacts
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/Bin'
    ArtifactName: Bin

- task: VSTest@2
  displayName: Test
  inputs:
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  condition: succeededOrFailed()
  displayName: Publish log artifacts
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/Logs'
    ArtifactName: Logs
