pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: VSBuild@1
  displayName: Build
  inputs:
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/restore'

- task: VSBuild@1
  displayName: Publish
  inputs:
    solution: Sideways
    configuration: '$(buildConfiguration)'
    msbuildArgs: '/t:Publish /p:PublishDir="$(Build.ArtifactStagingDirectory)/Bin"'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/Bin'
    ArtifactName: Bin

- task: VSTest@2
  displayName: Test
  inputs:
    configuration: '$(buildConfiguration)'