pool:
  vmImage: 'windows-latest'

steps:
- powershell: .\build.ps1
  displayName: Build and test

- task: PublishTestResults@2
  condition: succeededOrFailed()
  displayName: Publish test results
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: 'artifacts/Test results/*.trx'

- task: PublishBuildArtifacts@1
  condition: succeededOrFailed()
  displayName: Publish bin artifacts
  inputs:
    pathToPublish: 'artifacts/Bin'
    ArtifactName: Bin

- task: PublishBuildArtifacts@1
  condition: succeededOrFailed()
  displayName: Publish log artifacts
  inputs:
    pathToPublish: 'artifacts/Logs'
    ArtifactName: Logs
