namespace Sideways.AlphaVantage
{
    public enum Slice
    {
        Year1Month1,
        Year1Month2,
        Year1Month3,
        Year1Month4,
        Year1Month5,
        Year1Month6,
        Year1Month7,
        Year1Month8,
        Year1Month9,
        Year1Month10,
        Year1Month11,
        Year1Month12,
        Year2Month1,
        Year2Month2,
        Year2Month3,
        Year2Month4,
        Year2Month5,
        Year2Month6,
        Year2Month7,
        Year2Month8,
        Year2Month9,
        Year2Month10,
        Year2Month11,
        Year2Month12,
    }
}
