name: CI

on:
  push:
    branches: [ '*' ] # excludes tags
  pull_request: ~     # Pull requests to any branch should gain this status info

env:
  DOTNET_NOLOGO: true

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and test
      run: ./build.ps1

    - name: Upload bin artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Bin
        path: artifacts/Bin

    - name: Upload logs artifact
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Logs
        path: artifacts/Logs
